### ISSUE TITLE
attribute hidelogo doesn't work

### ISSUE THREAD

**Issue by markocupic** [altcha-org/altcha#15]
I try to use the widget with the hidelogo attribute but it does nothing. 

This is my markup: 
```<altcha-widget challengeurl="/_contao_altcha_challenge" hidelogo hidefooter></altcha-widget>```

**Comment by ovx** [comment]
Hi, thanks for reporting, its fixed in the latest version 0.1.6.

**Comment by markocupic** [comment]
Cool! Thank you!

**Comment by eduveks** [comment]
This bug is back in v3.0.9.

```html
<altcha-widget id="widgetAltcha" challenge="_{netuno-config=url-services}_altcha" language="_{netuno-config=language}" hideLogo hideFooter></altcha-widget>
```
