### ISSUE TITLE
Appearance Options

### ISSUE THREAD

**Issue by scottix** [altcha-org/altcha#16]
I know you have some appearance options, but even more would be nice. Particularly being able to set the width.

like width: 100%
I see max-width is set to 260px, but can't change that unless I do some manipulation.

See here below would be nice to have it full width.

![2024-02-21 10_25_12-Window](https://github.com/altcha-org/altcha/assets/435727/5d9a3c6f-6e76-4084-bff8-988c6c7a5b45)

**Comment by ovx** [comment]
Hi, thanks for the suggestion. It's okay to change the styling using the `.altcha` selector:

```css
.altcha {
  max-width: 100% !important;
}
```

But I also added a new css variable `--altcha-max-width` (from the version 0.1.7), so now you can do this:

```html
<altcha-widget
   style="--altcha-max-width:100%"
></altcha-widget>
```
