### ISSUE TITLE
[Feature] Add expiry property & Multi-threading

### ISSUE THREAD

**Issue by rallisf1** [altcha-org/altcha#18]
First of all thanks for making this, it is a great step towards the right direction.

The sad news is that the verification process on the client is terribly slow. About 40 seconds on my 3 year old i7-10870H laptop, which is beefier than most people's computers.

This leads to people leaving the form page (switching tabs) while it is verifying. That's not a terrible thing by itself but if you pair that with an expiry mechanism on the challenges, as rightfully suggested in the documentation, (I use redis on the server-side for this) then you get a user who waited a long time to submit a form and once he submits it he gets an error that his captcha has expired...

A temp solution is to apply `auto="onload"` but doesn't help much on small forms.

I tried decreasing the `maxnumber` iterations but all it did was fail the verification after pretty much the same time it took to verify before.  I suppose this is a bug but it's also a compromise on security.

### Proposal 1

Incorporate an `expiry` property (in seconds) that gets sent along with the challenge by the server. Once it expires trigger a `State.ERROR` with the appropriate message.

### Proposal 2

Apply multithreading. Spawn multiple workers and split the iterations between them.

What do you think?

**Comment by rallisf1** [comment]
### Proposal 3

Move the verification code to WASM (Rust ?). I know it won't do miracles but I'd say it would be 30% faster.

**Comment by ovx** [comment]
Hi there, thank you for your suggestions.

Firstly, it appears that the server is generating a random number that may be too large, causing complexity issues. Adjusting the maximum number generated by the server to around 100,000 should suffice for most cases. It's important to note that the `maxnumber` parameter on the widget only limits iterations on the client side and doesn't affect the server mechanism.

## Proposal 1

Incorporating the expire flag into the challenge would require changing the signature algorithm, as the current process is designed to be stateless. The expire flag would need to be signed as well. At present, it's recommended to include the timestamp in the salt (which is signed) and process it server-side upon verification.

Thus, I'm not in favor of incorporating this into the challenge. However, similar functionality can be achieved by adding this property to the widget. The error state would trigger after the specified time passes. Additionally, expiry can be auto-detected from the HTTP header (`Expires`). When expired, the widget can also automatically re-fetch the challenge.

## Proposal 2

This is indeed a good idea and should be implemented.

## Proposal 3

As I'm not an expert on WASM, I'm unsure about the extent to which this would benefit, considering the PoW involves hashing SHA, which I assume both JS and WASM utilize the same underlying crypto layer. Nevertheless, it's worth experimenting with.

Help wanted: This feature request is open to anyone who wants to contribute.

**Comment by rallisf1** [comment]
> Thus, I'm not in favor of incorporating this into the challenge. However, similar functionality can be achieved by adding this property to the widget. The error state would trigger after the specified time passes. Additionally, expiry can be auto-detected from the HTTP header (Expires). When expired, the widget can also automatically re-fetch the challenge.

You are right! This is a much better approach.

> I assume both JS and WASM utilize the same underlying crypto layer.

Actually no, WASM is actually bytecode and doesn't use any Javascript APIs. The language someone picks to code in makes a small difference, but not much. Rust is the go-to these days for such things, but you can compile WASM from pretty much every language.

AFAIK WASM doesn't support multithreading natively yet, you still have to use multiple workers. Thus, although good to experiment with, I think a WASM module for altcha can wait. Multithreading in plain JS (Proposal 2) will give a good enough boost.

P.S. I'll try to make time for this next week.

**Comment by ovx** [comment]
The multithreading support and the expire attribute are now implemented in the version 0.2.0.

Closing this issues, the WASM support is not a priority for now. Thank you for your help and contributions @rallisf1
