### ISSUE TITLE
[Bug] Not working - Multi-threading broke it

### ISSUE THREAD

**Issue by rallisf1** [altcha-org/altcha#20]
After latest 0.2.0 update the `solution` is always null.

I have confirmed `maxnumber` is the same between server and client and tried the `1e6` default.

I also tried disabling multi-threading by `workers="1"`, to no avail.

Did I miss something?

**Comment by ovx** [comment]
Hi, it seems to work fine. The only case, where I always get null is when the `maxnumber` is smaller than the actual random number generated on the server.

**Comment by rallisf1** [comment]
Ok got it. It seems it also fails when using exactly the same number, which is not intuitive.

Server: 1e6 / Client: 1e6 -> fails
Server: 1e6 -1 / Client: 1e6 -> verified

**Comment by ovx** [comment]
Fixed in 0.2.1. Thanks for reporting.
