### ISSUE TITLE
terraform + aws lambda + python implementation

### ISSUE THREAD

**Issue by mipmip** [altcha-org/altcha#24]
We've made an integration in our AWS-HTML-Form-Action terraform module.

- The repo is here: https://github.com/wearetechnative/terraform-aws-html-form-action
- An example is here: https://github.com/wearetechnative/terraform-aws-html-form-action/tree/main/examples/conf_in_tf_with_altcha

With this terraform module one can deploy a self hosted serverless form handler useful for static website.

We implemented the actual Altcha challenge creator and Altcha validation code as python without the need of external dependencies.

The python code is here: https://github.com/wearetechnative/terraform-aws-html-form-action/blob/main/lambda_src/html_form_action.py

**Comment by ovx** [comment]
Hi and thanks for the contribution. The link added to the docs https://altcha.org/docs/integrations/
