### ISSUE TITLE
Misleading error message "Error: Unknown algorithm value. Allowed values: SHA-256, SHA-384, SHA-512"

### ISSUE THREAD

**Issue by kzlucas** [altcha-org/altcha#3]
Hi, I'm trying to implement Altcha in an Angular Universal app, but I can't get Altcha to successfully verify the challenge. Here is the server response generated by the Node.js implementation of createALTCHA, copied from the documentation, using the `challengeurl` attribute:

```
{
    "alg": "SHA-256",
    "challenge": "5e4a93b74a3c81cb10818184381034b106dd25099ab2f7a52e376f2393093772",
    "salt": "6ccdc373959d74d3cf6bc56a",
    "signature": "b52cdb573507eb17943b45656fd122ea25c6e48eb2a565d7a2006e5ec603c677"
}
```

And here is the error message in the browser console:
``` ALTCHA Error: Unknown algorithm value. Allowed values: SHA-256, SHA-384, SHA-512 ```

I might be missing something in my implementation, but the error message is misleading because the challenge sent back by the server specifies "SHA-256," which is within the allowed values. Any input on this?

Thank you for this promising lib btw!

**Comment by ovx** [comment]
Hi, that's my mistake, the latest version of the widget expects `{ algorithm: 'SHA-256' }` (instead of `alg`), the docs are not updated yet.

**Comment by ovx** [comment]
The payload submitted to the server also contains `algorithm`.
