### ISSUE TITLE
Adjusting complexity server side question

### ISSUE THREAD

**Issue by lesar** [altcha-org/altcha#34]
All work well and I like altcha.  

I have read all document I have found but I have not understand how change complexity.  
I use the lib and this is a bit of my code:
```typescript
const challenge: Challenge  = await createChallenge({
  hmacKey: ALTCHA_API_SECRET
  , salt: salt()
  , saltLength: SaltLength
});
```
this code is on an entry point api on my server.  
can someone help me?
what is the complexity property to use to change complexity level how is write in the [manual](https://altcha.org/docs/complexity/)

I suppose to do something like this:  
```typescript
const challenge: Challenge  = await createChallenge({
  hmacKey: ALTCHA_API_SECRET
  , salt: salt()
  , saltLength: SaltLength
  , maxComplexity: 50000    <----------------- 
});
```

best regards,
Leonardo

**Comment by ixnas** [comment]
I believe the parameter is called `maxnumber`.

**Comment by ovx** [comment]
Yes, as ixnas pointed out, the name of the parameter is `maxnumber` as it refers to the maximum number returned from the random number generator. The "complexity" in the docs refers to the range between the minimum and the maximum, larger the range, greater the complexity. You can also generate the random number yourself and pass it directly using the `number` parameter for more control.
