### ISSUE TITLE
can't make it works in plain PHP

### ISSUE THREAD

**Issue by simon387** [altcha-org/altcha#40]
Hello,

dunno what I am doing wrong, but I can't make it work on a very easy plain html site;

1. I generated a free api key
2. I added this in the page inside form, and it works:

```
<altcha-widget
      challengeurl="https://eu.altcha.org/api/v1/challenge?apiKey=ckey_01e8b....bf35a5"
      debug
></altcha-widget>
```

3. I see this in the console:

```
ALTCHA fetching challenge from https://eu.altcha.org/api/v1/challenge?apiKey=...
altcha.min.js:7 ALTCHA expire 14400109
altcha.min.js:7 ALTCHA challenge {algorithm: 'SHA-256', challenge: '62859df29dbb78c6468c4ae1e...bee582ca2b707ce05', maxnumber: 20000, salt: 'db50d3e4ccae42517fb08c71?expires=1719003164', signature: 'fa04cdbeaa256bc2cc1744de8b8f8eb3c8...88bc344dfadad0d12bb'}
altcha.min.js:7 ALTCHA solution {number: 18523, took: 98, worker: true}
altcha.min.js:7 ALTCHA payload e...Q==
altcha.min.js:7 ALTCHA verified
```

4. when i submit the form, the PHP back end looks like this:

```
$token = $_POST['altcha'];
$publicKey = "ckey_01e8bb.....d9b63bf35a5";

$url = "https://eu.altcha.org/api/v1/verify?token=" . $token . "&apiKey=" . $publicKey;

$headers = [
	"Referer: myprodserver.it", // same one when i registered the api key
	"Authorization: Bearer " . $publicKey,
];

$options = [
	"http" => [
		"header" => implode("\r\n", $headers),
		"method" => "GET"
	]
];

$context = stream_context_create($options);

$response = file_get_contents($url, false, $context);
```

But i got 

```
Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
```

if i play a bit with the referer header i get a 404 (or a 403 if I change the auth header), what I am doing wrong? thank you

**Comment by ovx** [comment]
Hi, the server should respond with an explanation in the response body so always try to log that, it will help you understand what's going on.

To fix it:
1. The URL is wrong - use `POST /api/v1/challenge/verify`, also notice the POST method, you're sending GET
2. Set `content-type: application/json` header and include the body `{ "payload": "..." }` where the payload is the contents of `$_POST['altcha']`

API reference: https://altcha.org/api/operations/verifysolution/

**Comment by simon387** [comment]
thank you very much, now it work!
