### ISSUE TITLE
Missing SPAM filter options

### ISSUE THREAD

**Issue by MrTimber** [altcha-org/altcha#45]
As indicated on the README, options `email`, `expectedLanguages`, `expectedCountries`, `fields`, `ipAddress`, and `timeZone`
are available for the spam filter:

![image](https://github.com/altcha-org/altcha/assets/20933559/87357183-d918-4193-9156-e23445952b1e)

But some options [documented on the API](https://altcha.org/docs/api/spam-filter-api/#request) are missing: `blockedCountries`, `classifier`, `disableRules`, `text`:

![image](https://github.com/altcha-org/altcha/assets/20933559/022b60f6-2164-4289-9786-f99ccd2a16bd)

**So when we try to use one of these options on the Altcha widget, they are just ignored:**

![image](https://github.com/altcha-org/altcha/assets/20933559/a18c5dc2-2643-442d-96cc-8dd5c5e48bc5)

**Comment by MrTimber** [comment]
I opened a pull request: https://github.com/altcha-org/altcha/pull/46

**Comment by ovx** [comment]
Thanks for the PR, merged to the version `0.6.2`.

**Comment by MrTimber** [comment]
Thanks you!
