### ISSUE TITLE
SPAM filter: Fields hash verification fails when then there is a textarea field

### ISSUE THREAD

**Issue by MrTimber** [altcha-org/altcha#48]
Hi,

When using the SPAM filter, according to the documentation, after [checking the payload signature](https://altcha.org/docs/api/challenge-api/#verifying-the-signature), we also need to [verify the fields hash](https://altcha.org/docs/api/challenge-api/#verifying-fields):

![image](https://github.com/altcha-org/altcha/assets/20933559/44157d44-dc57-4dd6-b4fd-4aceb0c73af1)

But if there is a textarea field, the line endings sent to the web server in the POST data may be different from the line endings sent by the Alcha plugin for verification, depending on how the browser treats the line endings of textarea type fields.

Example:

- HTML form:
![image](https://github.com/altcha-org/altcha/assets/20933559/8751affd-698f-428c-8435-224e14e5ffdb)

- Data sent by the Altcha plugin; with only `\r` as end of line:
![image](https://github.com/altcha-org/altcha/assets/20933559/a6c5273e-c8ea-4d85-9027-f04ac06ed17b)

- Data received by the web server from the browser, with `\r\n` as end of line:
![image](https://github.com/altcha-org/altcha/assets/20933559/3440fd79-f5d4-4247-a058-88183186479a)

**So the verification of the fields hash by the web server fails.**

It would therefore be necessary either:
- guarantee that the Alcha plugin sends the same line endings for verification as those that the browser sends to the web server
- specify in the documentation that `\r\n` must be replaced by `\r` before checking the fields hash

**Comment by ovx** [comment]
Hi, thank you for reporting. It's a strange issues, when retrieving the value in JS using `element.value` browsers remove CR (\n) but by the HTML standard, they always submit CRLF sequence.  The widget (version `0.6.3`) now normalizes the value to CRLF so it should work just fine without any replacements on the server. Please give it a try.

**Comment by MrTimber** [comment]
Hi Daniel,

Yes it works now, thanks you.

Here is an interesting discussion about this subject: [What character represents a new line in a text area](https://stackoverflow.com/questions/14217101/what-character-represents-a-new-line-in-a-text-area)

![image](https://github.com/altcha-org/altcha/assets/20933559/19965d9f-cf7e-4c96-93b1-312eea3fc734)

Have a good day
