### ISSUE TITLE
Free API key: 401 Unauthorized / Too many workers

### ISSUE THREAD

**Issue by phuze** [altcha-org/altcha#49]
I am trying to register for a free API key here: https://altcha.org/docs/api/api_keys

After clicking generate, the loading indicator spins forever:

![image](https://github.com/user-attachments/assets/0658ee77-8d12-4987-9a6a-b5e9bf355cc7)

and this error appears in console:

![image](https://github.com/user-attachments/assets/b2149f2a-342a-449d-a7ab-32590beac3e1)

I'll note that I am based in Canada, and it appears to be calling your EU-based API: https://eu.altcha.org/api/v1/api_key/generate
Looking at your API documentation, there is a US-based API: https://us.altcha.org/api/v1/api_key/generate

Is your website meant to be calling the US-based API, for users outside the EU -- thus why I'm seeing the 401 Unauthorized?

**Comment by phuze** [comment]
Moved on to another project -- closing issue.

**Comment by ovx** [comment]
Hi, thanks for reporting. The 401 error is normal, the endpoint is protected with M2M Altcha; the other error with workers is fixed, affected only some devices. Free API Keys can be used across all regions, the EU endpoint is correct.
