### ISSUE TITLE
Documentation Proof of Work

### ISSUE THREAD

**Issue by RomainMularczyk** [altcha-org/altcha#5]
Hi, thanks for your work.

I struggle to understand how the PoW mechanism can really help in preventing spam and automated submissions of your forms. For example, if I write a selenium script, how would that really help in blocking the form I'm submitting automatically ?

**Comment by ovx** [comment]
Hi, thanks for the question, this needs to be documented better. I just published a documentation page explaining the effectiveness of ALTCHA (https://altcha.org/docs/effectiveness).

To your question about selenium: yes, of course, you can create scripts, just like you can create scripts to bypass reCAPTCHA using AI or any of the hundreds of cracking services you can find online.

ALTCHA is not a silver bullet that eliminates all spam, and it's not trying to be. The main focus here is GDPR compliance and the fact, that the majority of websites really don't need enterprise-grade spam protection.

**Comment by RomainMularczyk** [comment]
Makes sense, thanks for your answer :)

**Comment by RomainMularczyk** [comment]
Just read your new documentation page, it's really helpful, thanks. I worked on a Go implementation of the server side component, I can submit a PR if that can help and maybe work later on a Python version.

**Comment by ovx** [comment]
Yes, integrations are welcome, just create a new issue with the link to your repo and I'll put it in the documentation.
