### ISSUE TITLE
GET / POST requests for sending challenge and receiving response

### ISSUE THREAD

**Issue by DevRobi** [altcha-org/altcha#51]
Hi,
This is not really an issue I am just having a hard time sending the challenge to the captcha and receiving the response.
I implemented the pseudocode in the documentation that generates and verifies the challenges in python3.12.
How can I send it to the captcha service and get back the response for verification?
A quick python3.12 code examples would be much appreciated.
Thanks!

**Comment by ovx** [comment]
Hi,
To get the challenge to the widget, your server has to expose an endpoint such as `GET /altcha` which returns generated challenge as JSON. Configure this endpoint as `challengeurl` on the widget.

To verify the verification payload, the endpoint to which you submit the form (some `POST /submit` which is configured as `action` on your form) has to validate the field `altcha` from the POST data.

For Python, there's only this integration: https://github.com/wearetechnative/terraform-aws-html-form-action, you can see generation and verification in this file: https://github.com/wearetechnative/terraform-aws-html-form-action/blob/main/lambda_src/html_form_action.py

**Comment by DevRobi** [comment]
Thanks! I got it to a point where the GET request is working and altcha verifies by solving the pow challenges. The only thing that's not working is the POST requests.
Here is the JSON of my challenge:
{"algorithm": "SHA-256", "challenge": "b2e6358939f78bf5f2ad3964f774e835986c61f4502fe7cb57cb55c56553421a", "salt": "MDSrKjOvyz", "signature": "874b8d5b372d26420e98e35870eed687e669a4cbbe5661700a19ad0bc4023845"}
This is verified by altcha:
<img width="1511" alt="Screenshot 2024-07-21 at 3 40 16 PM" src="https://github.com/user-attachments/assets/8a6939cb-44fc-459f-b4c4-24efb48a1af7">
But then no POST request is fetched.

**Comment by ovx** [comment]
Hi, the widget only fetches and computes the solution. It includes a hidden input with the name `altcha` which contains the computed solution as base64 encoded string. The POST request is supposed to be made by the `<form>` element, when the user submits the form - you verify the `altcha` payload in the form handler.

If you have a different use-case, which does not include a form element, you can listen to the widget [events](https://github.com/altcha-org/altcha?tab=readme-ov-file#events) and get the payload from the widget there and verify it wherever you're submitting data.

**Comment by DevRobi** [comment]
I just forgot to include the parameter 'verifyurl' in altcha-widget that fixed the POST request. Thanks for your help a lot! Much appreciated.
