### ISSUE TITLE
Worker.js filename

### ISSUE THREAD

**Issue by Ian-Webb** [altcha-org/altcha#54]
To reduce the chance of filename clashes, would it be possible to change 'worker.js' to 'altcha-worker.js', or similar?

**Comment by ovx** [comment]
Hi, I assume your using the dist_external files. You can simply rename the wokrer.js and configure `workerurl` ([configuration](https://github.com/altcha-org/altcha?tab=readme-ov-file#configuration)) on the widget to point to your worker file.

**Comment by Ian-Webb** [comment]
Yes, you're absolutely correct. However, I would have to do this every time I downloaded an updated version of Altcha. And I have a terrible memory ;)

**Comment by ovx** [comment]
I would recommend creating an installation script that renames it for you.
