### ISSUE TITLE
Changing the URL-Response possible?

### ISSUE THREAD

**Issue by Fipschen** [altcha-org/altcha#55]
Hi there,

I'm using altcha with Angular frontend and Symfony backend. In the API for requests to the backend are some meta data in every response and the payload is as an property in the response. So the request of the Altcha request doesn't work because it's expects a `{ salt: ""}`, but get's an `{ data: { salt: "" }}`. 
Is there a possibility to customize the "data path" in the response? If not, I'll have build an exception for the altcha-requests to not send the meta data.

Thank you very much

**Comment by ovx** [comment]
Hi, if I understand the problem right, the server wraps the response with { data: ... }; there's not way to configure the widget for that behavior, you'll have to adjust your server to return JSON response without wrapping it.

**Comment by Fipschen** [comment]
Yes, that was the problem. I'd removed the wrapper for the altcha request, so now it work's.
Thank you
