### ISSUE TITLE
How to ensure POW-Results are not re-used

### ISSUE THREAD

**Issue by diesieben07** [altcha-org/altcha#57]
I am working on integrating Altcha into our site and I have come across a point that seems to disqualify Altcha entirely for me. Since there is zero state associated with the challenge (i.e. there is no nonce or something like that), how do we prevent a malicious client from simply skipping the challenge issued and just... re-using a previous challenge they did? Since the system is stateless, the parameters of the challenge are returned back to the server with the solution, so all the server can do is verify that the client responded with _a_ valid solution, not the solution to the challenge that was actually issued _for this form_.

Setting an expiry value is only a workaround imho.

**Comment by ovx** [comment]
Hi, for that purpose your server should store used challenges in to some sort of registry such as Redis and check the registry before validation. To make sure, that the challenge is issued to the specific form or page, add custom parameters to the `salt` as `<salt>?form_id=123` and check the parameters before validation (the parameters in the salt are part of the signature).

**Comment by diesieben07** [comment]
Thank you for your input. I think expiry value plus a Redis set could work for my needs.
