### ISSUE TITLE
No integration with forminator possible and destroys homepage

### ISSUE THREAD

**Issue by Kimosaj** [altcha-org/altcha#62]
Hi, I use Wordpress + Divi to build my homepage. I have installed Forminator and the Altcha Plugin and ran into two problems.

1. I can't find any options where to add Altcha as a field in any of my forms created with Forminator
2. When I enable captcha for any of the options (Forminator, custom html, etc.) and then go on my homepage, half of it isn't loading

Would be great to get some help. Thank you in advance

**Comment by ovx** [comment]
Hi, 

1. For Forminator, the ALTCHA widget is added automatically at the end of the form when rendered on page. You only have to enable the integration in the ALTCHA Plugin's Settings (Integrations -> Forminator -> Select Captcha).
2. If the page isn't loading properly, there will be something in the error logs to provide some more information.

**Comment by Kimosaj** [comment]
Thank you for the fast response.

1. Good to know that it actually just add a check at the end of the form (than isn't it maybe possible to add it to a form created with Divi?)
2. I found out that the rendering issues are caused by my caching plugin in combination with altcha

**Comment by Kimosaj** [comment]
Now my next problem is that the verification doesn't work. I use the free api for the plugin.

**Comment by ovx** [comment]
You're welcome. Divi form isn't supported, a proper integration requires server-side validation which is specific for the plugin so there's no workaround. The support for Divi form might be added in the future.
