### ISSUE TITLE
Js error

### ISSUE THREAD

**Issue by pippuccio76** [altcha-org/altcha#66]
Hi , i use your code , js and php...

PHP example have an error:

this: 
[CODE]
$payload = [
    'algorithm' => $challenge['algorithm'],
    'challenge' => $challenge['challenge'],
    'number'    => 12345, // Example number
    'salt'      => $challenge['salt'],
    'signature' => $challenge['signature'],
];

[/CODE]

must change to : 

[CODE]
        $payload = [
            'algorithm' => $challenge->algorithm,
            'challenge' => $challenge->challenge,
            'number'    => 43267, // Example number
            'salt'      => $challenge->salt,
            'signature' => $challenge->signature,
        ];

[/CODE] 

because return an object instead of array.

Now i have this error : 

altcha.js:1186 ALTCHA [name=altcha] SyntaxError: Unexpected token '<', "
<script  i"... is not valid JSON

How can i solve it ?

**Comment by ovx** [comment]
Hi, thanks for reporting, I'll fix the example.

Looks like the server doesn't return a valid JSON response. Check if the `challengeurl` is correct and inspect the server response - it must return only the JSON-encoded challenge and nothing else, also include `content-type: application/json` header.

**Comment by ovx** [comment]
The library `altcha-lib-php` is just a library, not a server and thus it does not encode any data. For more comprehensive example, please refer to the [altcha-starter-php](https://github.com/altcha-org/altcha-starter-php) repository, which includes a complete http server with encoding.

Make sure the response contains only the JSON-encoded challenge and nothing else.
