### ISSUE TITLE
Using `challengejson` renders captcha twice.

### ISSUE THREAD

**Issue by grantholle** [altcha-org/altcha#7]
I've got the following html:

```html
<altcha-widget class="altcha" challengejson="{&quot;algorithm&quot;:&quot;sha-256&quot;,&quot;challenge&quot;:&quot;7beab9a41258b00916ced3602e1f2d2638121ab60c8833f0339acbbb0fb63ccd&quot;,&quot;salt&quot;:&quot;33bf7740690e8082d40b0d08&quot;,&quot;signature&quot;:&quot;43bfee23a9605429a6f117c26b2231c6a2dfc7a80bb8dcaee213dc196b21f3ba&quot;}"></altcha-widget>
```

But on the page, it gets rendered twice:

<img width="426" alt="Screenshot 2024-01-12 at 12 43 26 PM" src="https://github.com/altcha-org/altcha/assets/1189456/1730a03c-8ac0-4ff5-b2f0-aed9de2fde19">

Clicking the top one checks immediately and has a state of verifying, but doesn't actually verify. The bottom captcha does verify correctly.

<img width="358" alt="Screenshot 2024-01-12 at 12 46 15 PM" src="https://github.com/altcha-org/altcha/assets/1189456/63240a40-d3d6-4657-b1dd-781f9c2b42fe">

**Comment by ovx** [comment]
Hi, so if you use `challengeurl` it renders correctly just once?

This double rendering could be an issue with live-reload, depends which framework are you using. I would try to build for production and see if it's still rendered twice. Don't really see a different reason for this.

Also, you have `sha-256` in the payload, which should trow an error because it must uppercased `SHA-256`.

**Comment by grantholle** [comment]
Yes, sorry that was an old snippet. I have changed it to have a `challengeurl` just to make sure. It's still rendering two elements inside the web component.

This is after verifying both,

<img width="491" alt="Screenshot 2024-01-12 at 10 10 46 PM" src="https://github.com/altcha-org/altcha/assets/1189456/46343dd1-52b0-4a7f-a345-0525937d8d96">

**Comment by grantholle** [comment]
I am using the cdn for this specific integration,

```html
<script async defer src="https://cdn.jsdelivr.net/npm/altcha/dist/altcha.js" type="module"></script>
```

Just to make sure I've removed the class attribute. I'm trying to get it working on a static site. It seems to happen right before `DOMContentLoaded` is fired. Could be a coincidence though

https://github.com/altcha-org/altcha/assets/1189456/8e52733b-3df1-43a6-8fd7-61d64efbfb18

**Comment by ovx** [comment]
Not sure why would that be happening, just tested it with the most basic example, and it works fine in chrome, firefox, safari:

```html
<html>
  <head>
  </head>
  <body>
    <form method="post" action="/">
      <input name="message" placeholder="Message..." />

      <altcha-widget
        id="altcha"
        challengeurl=""
        debug
        test
      ></altcha-widget>

      <button type="submit">Submit</button>
    </form>

    <script async defer src="https://cdn.jsdelivr.net/npm/altcha/dist/altcha.js" type="module"></script>
  </body>
</html>
```

The element `<altcha-widget>` should contain only one `.altcha` element, so somehow it renders twice in the same wrapper, could be something related to the shadow DOM.
 
Things to check:
- maybe you have some other javascript manipulating the form or the parent element?
- does the basic example (above) work fine?
- which browser are you using?

**Comment by grantholle** [comment]
Yes, it's related to your first point. The page is wrapped by Vue, which I had forgotten about. It seems to get re-rendered once Vue has mounted for some reason.

I had to follow the instructions in [this answer](https://stackoverflow.com/a/69657993/1696102). Thanks!

**Comment by grantholle** [comment]
I still can't get it working right when Vue mounts, but it has to do with Vue

**Comment by grantholle** [comment]
Yeah, Vue is doing something to cause it to re-render.

<img width="177" alt="Screenshot 2024-01-15 at 1 57 52 PM" src="https://github.com/altcha-org/altcha/assets/1189456/65d94f87-7344-4b95-a85e-5ecb90aecaed">

**Comment by ovx** [comment]
I just tested it with latest Vue (using `vite` and their vue template) and it works fine with both `<script>` and `import` installation methods. Renders correctly once, so it doesn't seem to be an issue related to Vue itself.

**Comment by grantholle** [comment]
Yes, I am using it with a 'normal' Vue implementation and it works lovely. The one I was struggling with when using the "browser" build. Ultimately, it's how my frontend is implemented coupled with the content from the CMS.

It's a long story, but I figured out a workaround that seems to be ok... Thanks again for the help.

**Comment by grantholle** [comment]
@alessandrobelli Ha, honestly, I'm having a hard time remembering...

I think what I'm doing is using [aryehraber/statamic-captcha](https://github.com/aryehraber/statamic-captcha) since it is a Statamic site I was having trouble with. I believe the solution was to inject the captcha after the DOM is loaded, or maybe with an `onMounted()` hook depending on your implementation.

The gist of it is:

```js
  document.addEventListener('DOMContentLoaded', function () {
    const wrapper = document.getElementById('altcha-widget')
    const captcha = document.createElement('altcha-widget')

    wrapper.getAttributeNames().forEach((name) => {
      captcha.setAttribute(name, wrapper.getAttribute(name))
    })

    wrapper.append(captcha)
    const form = captcha.closest('form')
    const hiddenInput = document.createElement('input')
    hiddenInput.setAttribute('type', 'hidden')
    hiddenInput.setAttribute('name', 'altcha-payload')

    // Append the hidden input to the form
    form.appendChild(hiddenInput)

    captcha.addEventListener('statechange', (ev) => {
      if (ev.detail.state === 'verified') {
        hiddenInput.setAttribute('value', ev.detail.payload)
      }
    })
  })
```
