### ISSUE TITLE
WebSockets integration

### ISSUE THREAD

**Issue by travisapple** [altcha-org/altcha#73]
First off, this project is fantastic, thank you!

Feature Request:

I'm trying to integrate this into a websockets project that has no form tag. The challenge comes in via websockets, the user solves the challenge and the result is sent out via websockets to a server that verifies it.

This code works:

	const altcha = document.createElement('altcha-widget')
	altcha.setAttribute('challengejson', JSON.stringify( challenge ))
	altcha.setAttribute('auto', 'onload')
	altcha.style.display = 'none'

	const c = document.querySelector('#container')
	c.append(altcha)

	await import('altcha.min.js')

	altcha.addEventListener('statechange', (ev) => {
		if (ev.detail.state == 'verified') {
			console.log('altcha done')
		}
	})

but it's pretty clunky using the dom when I don't need to. Is it possible to have something like this:

const result = await altcha.solve(challenge)

or maybe with a callback?

altcha.solve(challenge, (result)=>{
	console.log('altcha done')
})

**Comment by ovx** [comment]
Hi, for this purpose you can use the `solveChallenge` function from the `altcha-lib` package (https://github.com/altcha-org/altcha-lib?tab=readme-ov-file#solvechallengechallenge-salt-algorithm-max-start) which does not require DOM.

**Comment by travisapple** [comment]
Hey thanks OVX. That works

**Comment by ovx** [comment]
The package `altcha-lib` works also in the browsers, you have to install it instead of the widget.
