### ISSUE TITLE
Question RE: Integration outside of web forms

### ISSUE THREAD

**Issue by mooleshacat** [altcha-org/altcha#74]
Hi,

I have read the documentation and it only shows how to integrate it into a web form like so:
```
<form>
  <altcha-widget
    challengeurl="{YOUR_SERVER_HERE}"
  ></altcha-widget>
</form>
```

But it does not explain how to integrate it into a webpage (without a form)

The way I used reCaptcha was it was just on the page and it was able to run in the background on load and detect bots and block them. It wasn't attached to any specific form element.

Would I do the same thing by pasting the code anywhere on my page? Ex:
```
<body>
  ... bunch of website code ...

  <altcha-widget
    challengeurl="{YOUR_SERVER_HERE}"
  ></altcha-widget>
</body>
</html>
```

Or is this not going to work to secure the page in general like this?

I am trying to prevent bots from scraping my pages in general, I thought reCaptcha was nice but I'd like to de-google hence I ended up here at altcha :)

**Comment by ovx** [comment]
Hi, to integrate the widget without a `<form>` element, you would have to listen to [events](https://github.com/altcha-org/altcha?tab=readme-ov-file#events), specifically `verified` or `statechange`. From the event detail, you can get the altcha payload for verification and handle that according to your use case.

An alternative way is to use [altcha-lib](https://github.com/altcha-org/altcha-lib) package, which offers functions for challenge verification without any UI.

**Comment by mooleshacat** [comment]
Ok thank you :)
