### ISSUE TITLE
Unsafe check for SaaS

### ISSUE THREAD

**Issue by nijel** [altcha-org/altcha#76]
The following code matches when `.altcha.org` is anywhere in the URL including query string:

https://github.com/altcha-org/altcha/blob/fd1695c09ab2656394891ecff834eec62534b810/src/Altcha.svelte#L80

Looking at how `isFreeSaaS` is used, it seems harmless security wise, but it triggers security checkers once the library is used, for example CodeQL:

![obrazek](https://github.com/user-attachments/assets/fc6e2e79-0aa9-4146-9d43-9b4e53f5561b)

More info can be found at https://codeql.github.com/codeql-query-help/javascript/js-incomplete-url-substring-sanitization/

**Comment by ovx** [comment]
Hi, thanks for reporting, fixed in version 1.0.7.
