### ISSUE TITLE
ajax requests coming from the component not appearing as ajax requests

### ISSUE THREAD

**Issue by Fabio-Zeus-Soft** [altcha-org/altcha#81]
with some php frameworks, such as `codeigniter`, when working on the development environment all the non-ajax requests get some extra data attached to the server response (id est the debug bar)
this is happening with the altcha request for verifying the response, thus the challenge never gets verified
likely because by default javascript doesn't add the ajax request header, which allows the php framework to tell that's an ajax request so it won't ship the extra data in the response
more information [here](https://codeigniter4.github.io/CodeIgniter4/general/ajax.html)
i was wondering whether it could be possible to add the following code to the request created by the component
```javascript
headers: {
      "Content-Type": "application/json",
      "X-Requested-With": "XMLHttpRequest"
    }
```

**Comment by ovx** [comment]
Hi, this is something the framework should handle better, the altcha widget uses standard `fetch` and if the backend requires to detect fetch/xhr requests, it should use the modern alternative [`Sec-Fetch-Mode`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Mode).

But I think it can be useful to be able to add custom request headers, so it will be added in some of the future versions.

**Comment by ovx** [comment]
Support for a custom `fetch` function added in version 1.1.0. See the [docs](https://github.com/altcha-org/altcha?tab=readme-ov-file#custom-fetch-function) for more details.
