### ISSUE TITLE
Add support for 'credentials: "include" when fetching challenge

### ISSUE THREAD

**Issue by jonaskohl** [altcha-org/altcha#82]
I implemented the challenges server side by generating a new HMAC key for every session (via PHP). Thus, PHP sends a session ID via cookie to the client. The problem now is that the cookie gets ignored , because the ALTCHA widget does not include a `credentials: "include"` in [its `fetch()` call for requesting the challenge](https://github.com/altcha-org/altcha/blob/dc10c7262e102eda85e018ea63796d7b1c9c351e/src/Altcha.svelte#L231-L237). Thus, when I submit the form, a new session is created (and with it a new HMAC key), resulting in a signature mismatch. Would it be possible to add this option?

**Comment by ovx** [comment]
Hi, yes, this will be added soon with custom headers #81

**Comment by jonaskohl** [comment]
When that feature will be implemented, will it require manual handling of the Cookie header, or will this be handled by the browser or ALTCHA?  
Because having access to set a Cookie header is one thing, but automagically handling cookies via `credentials: "include"` is a whole different thing, as the latter leverages the browser's Cookie mechanism

**Comment by ovx** [comment]
It's currently implemented a custom fetch function. You can already give it try, the package is published as `1.1.0-beta.1`, requiring explicit installation of this version via npm. This version includes migration to Svelte5, so there might be bugs, please report any issues.

Documentation: https://github.com/altcha-org/altcha/tree/svelte5?tab=readme-ov-file#custom-fetch-function

**Comment by ovx** [comment]
Released as 1.1.0. See the [docs](https://github.com/altcha-org/altcha?tab=readme-ov-file#custom-fetch-function) for more details.

**Comment by jonaskohl** [comment]
Works perfectly for my use case! 👍 Thank you!
