### ISSUE TITLE
Initiate user verification manually

### ISSUE THREAD

**Issue by MarcusGitAccount** [altcha-org/altcha#83]
First of all, thank you very much for all the hard work that went into this project, I'm enjoying it.

Now, please excuse my lack of knowledge; I need some help please with setting up the widget in this way: when the user submits the form I want to perform some frontend validations and check-ups, and if those are alright I want to verify the user using the provided widget.

I know the verification can be initiated in the following manner:

```javascript
// Custom validation ...
// Form is valid, perform user verification ...
document.querySelector('altcha-widget')
        .verify()
        .then(token => {
            // Submit the form here
        }).catch(error => {
           // ...
        });
```

... but I couldn't find any way in the documentation(or the code) on how to prevent the automatic submission. The workaround I thought about was to place the widget outside the form, but that seems way too hack-ish.
Thank you in advance!

**Comment by ovx** [comment]
Hi, the widget does **not** automatically submit the form. The `verify` function only triggers the verification, but the form must be submitted using the usual submit button or via JS. In your code I see `// Submit the form here` so that's maybe the issue.
