### ISSUE TITLE
Typo in State.UNVERIFIED enum value

### ISSUE THREAD

**Issue by alexbcberio** [altcha-org/altcha#9]
The `State.UNVERIFIED` enum value has a typo with a value of "unverfied" instead of "unverified". Check the [source code](https://github.com/altcha-org/altcha/blob/fced018abeafd03a74833bb11868aedb0c090caa/src/types.ts#L37).

```diff
export enum State {
  ERROR = 'error',
  VERIFIED = 'verified',
  VERIFYING = 'verifying',
-  UNVERIFIED = 'unverfied',
+  UNVERIFIED = 'unverified',
};
```

**Comment by ovx** [comment]
Fixed in 0.1.4; thanks for reporting.
